#!/bin/bash


# https://stackoverflow.com/questions/23356779/how-can-i-store-find-command-result-as-arrays-in-bash
file_array=()
while IFS=  read -r -d $'\0'; do
		file_array+=("$REPLY")
done < <(find . -iname "*.sh" -print0)

#echo ${file_array[0]}

for currentFile in "${file_array[@]}"
do
	#echo "Run "$currentFile
	$currentFile
	wait
	#echo "Done!"
done
